test deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -124,12 +124,13 @@ deploy_job:
     - |
       mkdir -p ~/.ssh
       echo "DEBUG base64:"
-      echo "$SSH_PRIVATE_KEY" | base64 -d > /dev/null && echo "✅ base64 is valid" || echo "❌ base64 is invalid"
-      echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/gitlabrunner
+      echo "$SSH_PRIVATE_KEYY" | base64 -d > /dev/null && echo "✅ base64 is valid" || echo "❌ base64 is invalid"
+      echo "$SSH_PRIVATE_KEYY" | base64 -d > ~/.ssh/gitlabrunner
       chmod 600 ~/.ssh/gitlabrunner
       eval "$(ssh-agent -s)"
       ssh-add ~/.ssh/gitlabrunner
-      ssh-keyscan -H $APP_SERVER >> ~/ssh/known_host
+      # Ensure known_hosts is present for the target server
+      ssh-keyscan -H $APP_SERVER >> ~/.ssh/known_hosts
 
   script:
     - echo "Starting remote deploy..."
